frr defaults traditional
hostname r5
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.5/32
!
interface eth1
 description para-r2
 ip address 10.0.25.2/30
!
interface eth2
 description para-r4
 ip address 10.0.45.2/30
!
! BGP: sem IGP. iBGP pelo link direto com next-hop-self.
! 'no bgp ebgp-requires-policy': sem isso o FRR nao troca prefixos via eBGP.
router bgp 65003
 bgp router-id 10.255.0.5
 no bgp ebgp-requires-policy
 neighbor 10.0.25.1 remote-as 65001
 neighbor 10.0.45.1 remote-as 65002
 address-family ipv4 unicast
  network 10.255.0.5/32
 exit-address-family
!
