frr defaults traditional
hostname r3
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.3/32
!
interface eth1
 description para-r1
 ip address 10.0.13.2/30
!
interface eth2
 description para-r4
 ip address 10.0.34.1/30
!
! BGP: sem IGP. iBGP pelo link direto com next-hop-self.
! 'no bgp ebgp-requires-policy': sem isso o FRR nao troca prefixos via eBGP.
router bgp 65002
 bgp router-id 10.255.0.3
 no bgp ebgp-requires-policy
 neighbor 10.0.13.1 remote-as 65001
 neighbor 10.0.34.2 remote-as 65002
 address-family ipv4 unicast
  network 10.255.0.3/32
  neighbor 10.0.34.2 next-hop-self
 exit-address-family
!
