frr defaults traditional
hostname r4
service integrated-vtysh-config
!
interface lo
ip address 10.255.0.4/32
ip ospf area 0
!
interface eth1
description para-r2
ip address 10.0.24.2/30
ip ospf area 0
ip ospf network point-to-point
ip ospf cost 10
!
interface eth2
description para-r3
ip address 10.0.34.2/30
ip ospf area 0
ip ospf network point-to-point
ip ospf cost 10
!
interface eth3
description para-r5
ip address 10.0.45.1/30
ip ospf area 0
ip ospf network point-to-point
ip ospf cost 10
!
! Rede de acesso (LAN do h4): anunciada, mas passiva (sem Hellos para o host).
interface eth4
description lan-h4
ip address 192.168.4.1/24
ip ospf area 0
ip ospf passive
!
router ospf
ospf router-id 10.255.0.4
!
