frr defaults traditional
hostname r5
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.5/32
!
interface eth1
 description para-r2
 ip address 10.0.25.2/30
!
interface eth2
 description para-r4
 ip address 10.0.45.2/30
!
! Rede de acesso (LAN do h5)
interface eth3
 description lan-h5
 ip address 192.168.5.1/24
!
! RIPv2: anuncia os links (10.0.0.0/16), os loopbacks (10.255.0.0/24) e a LAN (passiva).
! Métrica = contagem de saltos. Timers padrão FRR: update 30s, timeout 180s, garbage 120s.
router rip
 version 2
 network 10.0.0.0/16
 network 10.255.0.0/24
 network 192.168.5.0/24
 passive-interface eth3
 redistribute connected
!
