frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
!
interface eth1
 description para-r1
 ip address 10.0.12.2/30
!
interface eth2
 description para-r4
 ip address 10.0.24.1/30
!
interface eth3
 description para-r5
 ip address 10.0.25.1/30
!
! Rede de acesso (LAN do h2)
interface eth4
 description lan-h2
 ip address 192.168.2.1/24
!
! BGP: sem IGP. iBGP pelo link direto com next-hop-self.
! 'no bgp ebgp-requires-policy': sem isso o FRR nao troca prefixos via eBGP.
router bgp 65001
 bgp router-id 10.255.0.2
 no bgp ebgp-requires-policy
 neighbor 10.0.12.1 remote-as 65001
 neighbor 10.0.24.2 remote-as 65002
 neighbor 10.0.25.2 remote-as 65003
 address-family ipv4 unicast
  network 10.255.0.2/32
  network 192.168.2.0/24
  neighbor 10.0.12.1 next-hop-self
 exit-address-family
!
